---
title: 'CCS Knowledge Map Results: Air Quality'
author: "Corey Jackson"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(DT)

air_survey <- read.csv("/Volumes/cbjackson2/ccs-knowledge/ccs-data/air-quality/air_survey.csv")
air_map <- read.csv("/Volumes/cbjackson2/ccs-knowledge/ccs-data/air-quality/air_map.csv")

# Questions - https://docs.google.com/document/d/1hl5Eb66a8j7TDE1EzzOF4eUjUguet5dMsw7UJydr_uY/edit

# Cleaning functions
clean_matrix <- function(dataframe, column_name) {
  cleaned_data <- dataframe %>%
    separate_rows({{ column_name }}, sep = "; ") %>%
    separate({{ column_name }}, into = c("question", "answer"), sep = " - ")
  cleaned_data$answer <- as.factor(cleaned_data$answer)
  
  summary_data <- cleaned_data %>%
    group_by(question, answer) %>%
    summarise(n = n()) %>%
    mutate(freq = round((n / sum(n)),digits=2     )*100)
  
  return(summary_data)
}


clean_box <- function(data, response) {
  summary_data <- data %>%
    group_by({{ response }}) %>%
    summarise(count = n()) %>%
    mutate(freq = round(count / sum(count), digits = 2)*100)
  
  return(summary_data)
}


clean_multi <- function(data, response) {
  cleaned_data <- data %>%
    separate_rows({{ response }}, sep = "; ")
  
  summary_data <- cleaned_data %>%
    group_by({{ response }}) %>%
    summarise(count = n()) %>%
    mutate(freq = round(count / sum(count), digits = 2) * 100)
  
  return(summary_data)
}
```

```{r}
names(air_survey)[5:14] <- c("Air.Quality.Experience",
               "Pollution.Health.Impact",
               "Pollution.Sources.Identification",
               "Quality.Change.Perception",
               "Vulnerable.Populations.Impact",
               "Contaminants.Awareness.Knowledge",
               "Sensor.Location.Suggestions",
               "Improvement.Actions.Taken",
               "Alert.Reception.Preference",
               "Deployment.Participation.Interest")

```


```{r}

air_box <- c(8,14)
air_box_col <- names(air_survey)[air_box]
air_multi <- c(2,3,6,7,9)+4
air_multi_col <- names(air_survey)[air_multi]
```

```{r}
library(rlang)
lapply(air_box_col, function(col) {
  col_sym <- sym(col)  # Convert string to symbol
  clean_box(air_survey, !!col_sym)  # Pass the symbol to clean_box
})

```

```{r}
lapply(air_multi_col, function(col) {
  col_sym <- sym(col)  # Convert string to symbol
  clean_multi(air_survey, !!col_sym)  # Pass the symbol to clean_box
})
```


## Air Quality (AQ)

```{r aq-setup, include=FALSE, cache=TRUE}

# Run all analysis for the AQ survey here

```

- Description of survey and the questions asked


### AQ Analysis
```{r aq-analysis-report, echo=TRUE}

# Report the analysis of survey items here

```

### AQ Map
```{r aq-map-report, echo=TRUE}

# Report the analysis of map items here

```



# Meta Summary


